"""empty message

Revision ID: 0716f6a87f3e
Revises: 20cdd90cfbce
Create Date: 2024-06-15 19:21:12.596831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0716f6a87f3e'
down_revision = '20cdd90cfbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('double_down',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('double_down',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
