"""empty message

Revision ID: ba570cbfdc5a
Revises: 822d1de81b2d
Create Date: 2024-06-14 18:11:46.280859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba570cbfdc5a'
down_revision = '822d1de81b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.String(length=40), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('deck',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('player_hand',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('dealer_hand',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('dealer_hand',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('player_hand',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('deck',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('winner')

    # ### end Alembic commands ###
